# Generated by Django 3.0.3 on 2020-04-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('img', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('status_text', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
    ]
